// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddHostGroup(arg1:models.HostGroup):Promise<void>;

export function ApplyHosts():Promise<void>;

export function BackupAppAndSystemHosts():Promise<string>;

export function BackupConfig():Promise<void>;

export function BackupData():Promise<void>;

export function CreateSystemHostsBackup():Promise<string>;

export function DeleteHostGroup(arg1:string):Promise<void>;

export function GetConfig():Promise<models.AppConfig>;

export function GetHostGroup(arg1:string):Promise<models.HostGroup>;

export function GetHostGroups():Promise<Array<models.HostGroup>>;

export function GetRemoteContent(arg1:string):Promise<string>;

export function GetSystemHostPath():Promise<string>;

export function GetSystemHostsContent():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function RefreshRemoteGroup(arg1:string):Promise<void>;

export function RefreshRemoteGroups():Promise<void>;

export function ToggleHostGroup(arg1:string,arg2:boolean):Promise<void>;

export function UpdateConfig(arg1:models.AppConfig):Promise<void>;

export function UpdateHostGroup(arg1:models.HostGroup):Promise<void>;
