// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHostGroup(arg1) {
  return window['go']['main']['App']['AddHostGroup'](arg1);
}

export function ApplyHosts() {
  return window['go']['main']['App']['ApplyHosts']();
}

export function DeleteHostGroup(arg1) {
  return window['go']['main']['App']['DeleteHostGroup'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHostGroup(arg1) {
  return window['go']['main']['App']['GetHostGroup'](arg1);
}

export function GetHostGroups() {
  return window['go']['main']['App']['GetHostGroups']();
}

export function GetRemoteContent(arg1) {
  return window['go']['main']['App']['GetRemoteContent'](arg1);
}

export function GetSystemHostPath() {
  return window['go']['main']['App']['GetSystemHostPath']();
}

export function GetSystemHostsContent() {
  return window['go']['main']['App']['GetSystemHostsContent']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RefreshRemoteGroups() {
  return window['go']['main']['App']['RefreshRemoteGroups']();
}

export function ToggleHostGroup(arg1, arg2) {
  return window['go']['main']['App']['ToggleHostGroup'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateHostGroup(arg1) {
  return window['go']['main']['App']['UpdateHostGroup'](arg1);
}
